# Generated by Django 4.1.3 on 2023-05-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='author',
        ),
    ]
